apiVersion: apps/v1
kind: Deployment
metadata:
  name: vision-go-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vision-go-app
  template:
    metadata:
      labels:
        app: vision-go-app
    spec:
      containers:
        - name: vision-go-app
          image: asia-northeast3-docker.pkg.dev/gcloud-jho/gke-vision-repo/vision-go-demo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vision-go-service
spec:
  type: NodePort
  selector:
    app: vision-go-app
  ports:
    - port: 80
      targetPort: 8080